title: "Satya Gopal's Blogs"
email: kodukulasatyagopal@gmail.com
description: >-
  Decoding technical concepts, research, and ideas through my lens of learning and curiosity.
linkedin: https://www.linkedin.com/in/satyagopal-kodukula-8840bb217
github_username: SatyagopalK
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages
  - _sass
  - _includes

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Satya Gopal Kodukula"
  avatar : "assets/images/gopal_image.jpg"
  bio    : "Decoding technical concepts, research, and ideas through my lens of learning and curiosity."
  links:
    - label: "Personal Website"
      icon: "fas fa-fw fa-link"
      url: "https://satyagopalk.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/satyagopal-kodukula-8840bb217"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SatyagopalK"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/satyagopal-kodukula-8840bb217"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SatyagopalK"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
